### ISSUE TITLE
Source Folder wrong label

### ISSUE THREAD

**Issue by lloyda** [HighEncryption/SyncPro#47]
Using build 0.0.2, and setting up OneDrive as source, when choosing the source folder the dialog box for browsing says 'Select the destination folder'.  Obviously should be source

**Comment by HighEncryption** [comment]
Thanks @lloyda. Can you attach a screenshot?

**Comment by lloyda** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/1671197/41620773-a00ae87a-7402-11e8-938a-3009adddeb9a.png)

**Comment by HighEncryption** [comment]
Click on the triangle to the left of the cloud icon.

Also, a word of warning (since you are the first user to try this out other than me): Please try this out on a test OneDrive account before using this for anything "important", and be sure your data is backed up first. I've done a lot of testing, but I also don't want anything to happen to your data.

**Comment by lloyda** [comment]
I think you have misunderstood the issue. It's trivial, but the wording in the "Browse for Folder" pop up is wrong. I'm selecting a **source** folder, not a **destination** one.  I understand how to expand the tree, but I'm not about to reveal the contents of my one drive on a public site!

**Comment by HighEncryption** [comment]
Yes, I see what you are referring to now. I misread your original issue and thought that you were having trouble selecting a folder. And no, I wasn't asking you to post a screenshot of your data.

Thanks for the issue. I will put it in for the next milestone.
